name             'b9centos'
maintainer       'Chris Escalante'
maintainer_email 'chris@beyond9.co'
license          'All rights reserved'
description      'Core Image for B9 Vagrant'
version          '7.0.0'