name             'b9base'
maintainer       'Chris Escalante'
maintainer_email 'chris@beyond9.co'
license          'All rights reserved'
description      'Installs/Configures Ruby'
version          '0.0.1'

depends 'rvm'
depends 'yum'
depends 'yum-epel'
depends 'yum-percona'
depends 'percona'
depends 'mysql'
depends 'b9php'
depends 'b9ruby'
depends 'b9apache'
depends 'b9ruby'
depends 'b9npm'